// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: v1/module.proto

package gimpelv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Module-to-Agent Communication (used by honeypot modules)
type ConnectionInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConnectionId  string                 `protobuf:"bytes,1,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	SourceIp      string                 `protobuf:"bytes,2,opt,name=source_ip,json=sourceIp,proto3" json:"source_ip,omitempty"`
	SourcePort    uint32                 `protobuf:"varint,3,opt,name=source_port,json=sourcePort,proto3" json:"source_port,omitempty"`
	DestIp        string                 `protobuf:"bytes,4,opt,name=dest_ip,json=destIp,proto3" json:"dest_ip,omitempty"`
	DestPort      uint32                 `protobuf:"varint,5,opt,name=dest_port,json=destPort,proto3" json:"dest_port,omitempty"`
	Protocol      string                 `protobuf:"bytes,6,opt,name=protocol,proto3" json:"protocol,omitempty"`
	TimestampNs   int64                  `protobuf:"varint,7,opt,name=timestamp_ns,json=timestampNs,proto3" json:"timestamp_ns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectionInfo) Reset() {
	*x = ConnectionInfo{}
	mi := &file_v1_module_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionInfo) ProtoMessage() {}

func (x *ConnectionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_v1_module_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionInfo.ProtoReflect.Descriptor instead.
func (*ConnectionInfo) Descriptor() ([]byte, []int) {
	return file_v1_module_proto_rawDescGZIP(), []int{0}
}

func (x *ConnectionInfo) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

func (x *ConnectionInfo) GetSourceIp() string {
	if x != nil {
		return x.SourceIp
	}
	return ""
}

func (x *ConnectionInfo) GetSourcePort() uint32 {
	if x != nil {
		return x.SourcePort
	}
	return 0
}

func (x *ConnectionInfo) GetDestIp() string {
	if x != nil {
		return x.DestIp
	}
	return ""
}

func (x *ConnectionInfo) GetDestPort() uint32 {
	if x != nil {
		return x.DestPort
	}
	return 0
}

func (x *ConnectionInfo) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *ConnectionInfo) GetTimestampNs() int64 {
	if x != nil {
		return x.TimestampNs
	}
	return 0
}

type HandleConnectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Connection    *ConnectionInfo        `protobuf:"bytes,1,opt,name=connection,proto3" json:"connection,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandleConnectionRequest) Reset() {
	*x = HandleConnectionRequest{}
	mi := &file_v1_module_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandleConnectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleConnectionRequest) ProtoMessage() {}

func (x *HandleConnectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_module_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleConnectionRequest.ProtoReflect.Descriptor instead.
func (*HandleConnectionRequest) Descriptor() ([]byte, []int) {
	return file_v1_module_proto_rawDescGZIP(), []int{1}
}

func (x *HandleConnectionRequest) GetConnection() *ConnectionInfo {
	if x != nil {
		return x.Connection
	}
	return nil
}

type HandleConnectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	DataPort      int32                  `protobuf:"varint,2,opt,name=data_port,json=dataPort,proto3" json:"data_port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandleConnectionResponse) Reset() {
	*x = HandleConnectionResponse{}
	mi := &file_v1_module_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandleConnectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleConnectionResponse) ProtoMessage() {}

func (x *HandleConnectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_module_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleConnectionResponse.ProtoReflect.Descriptor instead.
func (*HandleConnectionResponse) Descriptor() ([]byte, []int) {
	return file_v1_module_proto_rawDescGZIP(), []int{2}
}

func (x *HandleConnectionResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *HandleConnectionResponse) GetDataPort() int32 {
	if x != nil {
		return x.DataPort
	}
	return 0
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_v1_module_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_module_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_v1_module_proto_rawDescGZIP(), []int{3}
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_v1_module_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_module_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_v1_module_proto_rawDescGZIP(), []int{4}
}

func (x *HealthCheckResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthCheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthCheckResponse) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type ModuleManifest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModuleId      string                 `protobuf:"bytes,1,opt,name=module_id,json=moduleId,proto3" json:"module_id,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	PayloadSha256 string                 `protobuf:"bytes,3,opt,name=payload_sha256,json=payloadSha256,proto3" json:"payload_sha256,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModuleManifest) Reset() {
	*x = ModuleManifest{}
	mi := &file_v1_module_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModuleManifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModuleManifest) ProtoMessage() {}

func (x *ModuleManifest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_module_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModuleManifest.ProtoReflect.Descriptor instead.
func (*ModuleManifest) Descriptor() ([]byte, []int) {
	return file_v1_module_proto_rawDescGZIP(), []int{5}
}

func (x *ModuleManifest) GetModuleId() string {
	if x != nil {
		return x.ModuleId
	}
	return ""
}

func (x *ModuleManifest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ModuleManifest) GetPayloadSha256() string {
	if x != nil {
		return x.PayloadSha256
	}
	return ""
}

func (x *ModuleManifest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// ModuleImage represents a signed, deployable honeypot module
type ModuleImage struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Id          string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Version     string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Description string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	ImageRef    string                 `protobuf:"bytes,5,opt,name=image_ref,json=imageRef,proto3" json:"image_ref,omitempty"` // OCI image reference
	Digest      string                 `protobuf:"bytes,6,opt,name=digest,proto3" json:"digest,omitempty"`                     // SHA256 of the image payload
	SizeBytes   int64                  `protobuf:"varint,7,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	Manifest    []byte                 `protobuf:"bytes,8,opt,name=manifest,proto3" json:"manifest,omitempty"`                  // Serialized ModuleManifest
	Signature   []byte                 `protobuf:"bytes,9,opt,name=signature,proto3" json:"signature,omitempty"`                // Ed25519 signature of the manifest
	SignedBy    string                 `protobuf:"bytes,10,opt,name=signed_by,json=signedBy,proto3" json:"signed_by,omitempty"` // Key ID
	SignedAt    int64                  `protobuf:"varint,11,opt,name=signed_at,json=signedAt,proto3" json:"signed_at,omitempty"`
	// Runtime requirements
	RequiredCapabilities []string `protobuf:"bytes,12,rep,name=required_capabilities,json=requiredCapabilities,proto3" json:"required_capabilities,omitempty"` // Linux capabilities (e.g., "NET_BIND_SERVICE")
	RequiresPrivileged   bool     `protobuf:"varint,13,opt,name=requires_privileged,json=requiresPrivileged,proto3" json:"requires_privileged,omitempty"`      // Needs privileged container
	MinAgentVersion      string   `protobuf:"bytes,14,opt,name=min_agent_version,json=minAgentVersion,proto3" json:"min_agent_version,omitempty"`              // Minimum agent version required
	// Protocol support
	Protocols []*ModuleProtocol `protobuf:"bytes,15,rep,name=protocols,proto3" json:"protocols,omitempty"`
	// Resource recommendations
	Resources *ResourceRequirements `protobuf:"bytes,16,opt,name=resources,proto3" json:"resources,omitempty"`
	// Metadata
	Labels        map[string]string `protobuf:"bytes,17,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CreatedAt     int64             `protobuf:"varint,18,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64             `protobuf:"varint,19,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModuleImage) Reset() {
	*x = ModuleImage{}
	mi := &file_v1_module_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModuleImage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModuleImage) ProtoMessage() {}

func (x *ModuleImage) ProtoReflect() protoreflect.Message {
	mi := &file_v1_module_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModuleImage.ProtoReflect.Descriptor instead.
func (*ModuleImage) Descriptor() ([]byte, []int) {
	return file_v1_module_proto_rawDescGZIP(), []int{6}
}

func (x *ModuleImage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ModuleImage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ModuleImage) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ModuleImage) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ModuleImage) GetImageRef() string {
	if x != nil {
		return x.ImageRef
	}
	return ""
}

func (x *ModuleImage) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

func (x *ModuleImage) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *ModuleImage) GetManifest() []byte {
	if x != nil {
		return x.Manifest
	}
	return nil
}

func (x *ModuleImage) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *ModuleImage) GetSignedBy() string {
	if x != nil {
		return x.SignedBy
	}
	return ""
}

func (x *ModuleImage) GetSignedAt() int64 {
	if x != nil {
		return x.SignedAt
	}
	return 0
}

func (x *ModuleImage) GetRequiredCapabilities() []string {
	if x != nil {
		return x.RequiredCapabilities
	}
	return nil
}

func (x *ModuleImage) GetRequiresPrivileged() bool {
	if x != nil {
		return x.RequiresPrivileged
	}
	return false
}

func (x *ModuleImage) GetMinAgentVersion() string {
	if x != nil {
		return x.MinAgentVersion
	}
	return ""
}

func (x *ModuleImage) GetProtocols() []*ModuleProtocol {
	if x != nil {
		return x.Protocols
	}
	return nil
}

func (x *ModuleImage) GetResources() *ResourceRequirements {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *ModuleImage) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *ModuleImage) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *ModuleImage) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

// ModuleProtocol describes a protocol the module supports
type ModuleProtocol struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Name            string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // "ssh", "http", "smtp", etc...
	DefaultPort     uint32                 `protobuf:"varint,2,opt,name=default_port,json=defaultPort,proto3" json:"default_port,omitempty"`
	HighInteraction bool                   `protobuf:"varint,3,opt,name=high_interaction,json=highInteraction,proto3" json:"high_interaction,omitempty"` // Supports high-interaction mode
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ModuleProtocol) Reset() {
	*x = ModuleProtocol{}
	mi := &file_v1_module_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModuleProtocol) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModuleProtocol) ProtoMessage() {}

func (x *ModuleProtocol) ProtoReflect() protoreflect.Message {
	mi := &file_v1_module_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModuleProtocol.ProtoReflect.Descriptor instead.
func (*ModuleProtocol) Descriptor() ([]byte, []int) {
	return file_v1_module_proto_rawDescGZIP(), []int{7}
}

func (x *ModuleProtocol) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ModuleProtocol) GetDefaultPort() uint32 {
	if x != nil {
		return x.DefaultPort
	}
	return 0
}

func (x *ModuleProtocol) GetHighInteraction() bool {
	if x != nil {
		return x.HighInteraction
	}
	return false
}

// ResourceRequirements specifies **recommended** resource limits
type ResourceRequirements struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemoryMb      int64                  `protobuf:"varint,1,opt,name=memory_mb,json=memoryMb,proto3" json:"memory_mb,omitempty"`
	CpuMillicores int32                  `protobuf:"varint,2,opt,name=cpu_millicores,json=cpuMillicores,proto3" json:"cpu_millicores,omitempty"`
	DiskMb        int64                  `protobuf:"varint,3,opt,name=disk_mb,json=diskMb,proto3" json:"disk_mb,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceRequirements) Reset() {
	*x = ResourceRequirements{}
	mi := &file_v1_module_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceRequirements) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceRequirements) ProtoMessage() {}

func (x *ResourceRequirements) ProtoReflect() protoreflect.Message {
	mi := &file_v1_module_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceRequirements.ProtoReflect.Descriptor instead.
func (*ResourceRequirements) Descriptor() ([]byte, []int) {
	return file_v1_module_proto_rawDescGZIP(), []int{8}
}

func (x *ResourceRequirements) GetMemoryMb() int64 {
	if x != nil {
		return x.MemoryMb
	}
	return 0
}

func (x *ResourceRequirements) GetCpuMillicores() int32 {
	if x != nil {
		return x.CpuMillicores
	}
	return 0
}

func (x *ResourceRequirements) GetDiskMb() int64 {
	if x != nil {
		return x.DiskMb
	}
	return 0
}

// ModuleCatalog contains all available modules
type ModuleCatalog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Modules       []*ModuleImage         `protobuf:"bytes,1,rep,name=modules,proto3" json:"modules,omitempty"`                       // List of available modules
	Version       int64                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`                      // Catalog version (monotonically increasing)
	UpdatedAt     int64                  `protobuf:"varint,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"` // Last update timestamp
	Signature     []byte                 `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`                   // Ed25519 signature of the entire catalog
	SignedBy      string                 `protobuf:"bytes,5,opt,name=signed_by,json=signedBy,proto3" json:"signed_by,omitempty"`     // Key ID that signed this catalog
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModuleCatalog) Reset() {
	*x = ModuleCatalog{}
	mi := &file_v1_module_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModuleCatalog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModuleCatalog) ProtoMessage() {}

func (x *ModuleCatalog) ProtoReflect() protoreflect.Message {
	mi := &file_v1_module_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModuleCatalog.ProtoReflect.Descriptor instead.
func (*ModuleCatalog) Descriptor() ([]byte, []int) {
	return file_v1_module_proto_rawDescGZIP(), []int{9}
}

func (x *ModuleCatalog) GetModules() []*ModuleImage {
	if x != nil {
		return x.Modules
	}
	return nil
}

func (x *ModuleCatalog) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ModuleCatalog) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *ModuleCatalog) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *ModuleCatalog) GetSignedBy() string {
	if x != nil {
		return x.SignedBy
	}
	return ""
}

// ModuleAssignment assigns specific modules to an agent
type ModuleAssignment struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	ModuleId string                 `protobuf:"bytes,1,opt,name=module_id,json=moduleId,proto3" json:"module_id,omitempty"` // Module to deploy
	Version  string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`                   // Specific version (or "latest")
	// Listener configuration
	Listeners []*ListenerAssignment `protobuf:"bytes,3,rep,name=listeners,proto3" json:"listeners,omitempty"`
	// Override environment variables
	Env map[string]string `protobuf:"bytes,4,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Override resource limits
	ResourceOverrides *ResourceRequirements `protobuf:"bytes,5,opt,name=resource_overrides,json=resourceOverrides,proto3" json:"resource_overrides,omitempty"`
	// Execution preferences
	ExecutionMode  string `protobuf:"bytes,6,opt,name=execution_mode,json=executionMode,proto3" json:"execution_mode,omitempty"`    // "containerd", "userspace", etc.
	ConnectionMode string `protobuf:"bytes,7,opt,name=connection_mode,json=connectionMode,proto3" json:"connection_mode,omitempty"` // "tcp_relay", "fdpass", etc.
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ModuleAssignment) Reset() {
	*x = ModuleAssignment{}
	mi := &file_v1_module_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModuleAssignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModuleAssignment) ProtoMessage() {}

func (x *ModuleAssignment) ProtoReflect() protoreflect.Message {
	mi := &file_v1_module_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModuleAssignment.ProtoReflect.Descriptor instead.
func (*ModuleAssignment) Descriptor() ([]byte, []int) {
	return file_v1_module_proto_rawDescGZIP(), []int{10}
}

func (x *ModuleAssignment) GetModuleId() string {
	if x != nil {
		return x.ModuleId
	}
	return ""
}

func (x *ModuleAssignment) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ModuleAssignment) GetListeners() []*ListenerAssignment {
	if x != nil {
		return x.Listeners
	}
	return nil
}

func (x *ModuleAssignment) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *ModuleAssignment) GetResourceOverrides() *ResourceRequirements {
	if x != nil {
		return x.ResourceOverrides
	}
	return nil
}

func (x *ModuleAssignment) GetExecutionMode() string {
	if x != nil {
		return x.ExecutionMode
	}
	return ""
}

func (x *ModuleAssignment) GetConnectionMode() string {
	if x != nil {
		return x.ConnectionMode
	}
	return ""
}

// ListenerAssignment configures a listener for a module
type ListenerAssignment struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // Listener ID
	Protocol        string                 `protobuf:"bytes,2,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Port            uint32                 `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	HighInteraction bool                   `protobuf:"varint,4,opt,name=high_interaction,json=highInteraction,proto3" json:"high_interaction,omitempty"` // Enable high-interaction mode
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListenerAssignment) Reset() {
	*x = ListenerAssignment{}
	mi := &file_v1_module_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListenerAssignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListenerAssignment) ProtoMessage() {}

func (x *ListenerAssignment) ProtoReflect() protoreflect.Message {
	mi := &file_v1_module_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListenerAssignment.ProtoReflect.Descriptor instead.
func (*ListenerAssignment) Descriptor() ([]byte, []int) {
	return file_v1_module_proto_rawDescGZIP(), []int{11}
}

func (x *ListenerAssignment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ListenerAssignment) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *ListenerAssignment) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ListenerAssignment) GetHighInteraction() bool {
	if x != nil {
		return x.HighInteraction
	}
	return false
}

// AgentModuleConfig contains all module assignments for an agent
type AgentModuleConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Assignments   []*ModuleAssignment    `protobuf:"bytes,2,rep,name=assignments,proto3" json:"assignments,omitempty"`
	Version       int64                  `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`    // Config version
	Signature     []byte                 `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"` // Signature of this config
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentModuleConfig) Reset() {
	*x = AgentModuleConfig{}
	mi := &file_v1_module_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentModuleConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentModuleConfig) ProtoMessage() {}

func (x *AgentModuleConfig) ProtoReflect() protoreflect.Message {
	mi := &file_v1_module_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentModuleConfig.ProtoReflect.Descriptor instead.
func (*AgentModuleConfig) Descriptor() ([]byte, []int) {
	return file_v1_module_proto_rawDescGZIP(), []int{12}
}

func (x *AgentModuleConfig) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentModuleConfig) GetAssignments() []*ModuleAssignment {
	if x != nil {
		return x.Assignments
	}
	return nil
}

func (x *AgentModuleConfig) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *AgentModuleConfig) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

// Module Catalog Service (Master-side)
type GetCatalogRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CurrentVersion int64                  `protobuf:"varint,1,opt,name=current_version,json=currentVersion,proto3" json:"current_version,omitempty"` // Client's current catalog version (0 for first request)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetCatalogRequest) Reset() {
	*x = GetCatalogRequest{}
	mi := &file_v1_module_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCatalogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCatalogRequest) ProtoMessage() {}

func (x *GetCatalogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_module_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCatalogRequest.ProtoReflect.Descriptor instead.
func (*GetCatalogRequest) Descriptor() ([]byte, []int) {
	return file_v1_module_proto_rawDescGZIP(), []int{13}
}

func (x *GetCatalogRequest) GetCurrentVersion() int64 {
	if x != nil {
		return x.CurrentVersion
	}
	return 0
}

type GetCatalogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Updated       bool                   `protobuf:"varint,1,opt,name=updated,proto3" json:"updated,omitempty"` // True if catalog has updates
	Catalog       *ModuleCatalog         `protobuf:"bytes,2,opt,name=catalog,proto3" json:"catalog,omitempty"`  // Full catalog (only if updated)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCatalogResponse) Reset() {
	*x = GetCatalogResponse{}
	mi := &file_v1_module_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCatalogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCatalogResponse) ProtoMessage() {}

func (x *GetCatalogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_module_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCatalogResponse.ProtoReflect.Descriptor instead.
func (*GetCatalogResponse) Descriptor() ([]byte, []int) {
	return file_v1_module_proto_rawDescGZIP(), []int{14}
}

func (x *GetCatalogResponse) GetUpdated() bool {
	if x != nil {
		return x.Updated
	}
	return false
}

func (x *GetCatalogResponse) GetCatalog() *ModuleCatalog {
	if x != nil {
		return x.Catalog
	}
	return nil
}

type GetModuleAssignmentsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AgentId        string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	CurrentVersion int64                  `protobuf:"varint,2,opt,name=current_version,json=currentVersion,proto3" json:"current_version,omitempty"` // Client's current config version
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetModuleAssignmentsRequest) Reset() {
	*x = GetModuleAssignmentsRequest{}
	mi := &file_v1_module_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetModuleAssignmentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModuleAssignmentsRequest) ProtoMessage() {}

func (x *GetModuleAssignmentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_module_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModuleAssignmentsRequest.ProtoReflect.Descriptor instead.
func (*GetModuleAssignmentsRequest) Descriptor() ([]byte, []int) {
	return file_v1_module_proto_rawDescGZIP(), []int{15}
}

func (x *GetModuleAssignmentsRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *GetModuleAssignmentsRequest) GetCurrentVersion() int64 {
	if x != nil {
		return x.CurrentVersion
	}
	return 0
}

type GetModuleAssignmentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Updated       bool                   `protobuf:"varint,1,opt,name=updated,proto3" json:"updated,omitempty"`
	Config        *AgentModuleConfig     `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetModuleAssignmentsResponse) Reset() {
	*x = GetModuleAssignmentsResponse{}
	mi := &file_v1_module_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetModuleAssignmentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModuleAssignmentsResponse) ProtoMessage() {}

func (x *GetModuleAssignmentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_module_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModuleAssignmentsResponse.ProtoReflect.Descriptor instead.
func (*GetModuleAssignmentsResponse) Descriptor() ([]byte, []int) {
	return file_v1_module_proto_rawDescGZIP(), []int{16}
}

func (x *GetModuleAssignmentsResponse) GetUpdated() bool {
	if x != nil {
		return x.Updated
	}
	return false
}

func (x *GetModuleAssignmentsResponse) GetConfig() *AgentModuleConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type DownloadModuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModuleId      string                 `protobuf:"bytes,1,opt,name=module_id,json=moduleId,proto3" json:"module_id,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"` // Specific version or "latest"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadModuleRequest) Reset() {
	*x = DownloadModuleRequest{}
	mi := &file_v1_module_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadModuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadModuleRequest) ProtoMessage() {}

func (x *DownloadModuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_module_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadModuleRequest.ProtoReflect.Descriptor instead.
func (*DownloadModuleRequest) Descriptor() ([]byte, []int) {
	return file_v1_module_proto_rawDescGZIP(), []int{17}
}

func (x *DownloadModuleRequest) GetModuleId() string {
	if x != nil {
		return x.ModuleId
	}
	return ""
}

func (x *DownloadModuleRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type ModuleImageChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`                             // Chunk of image data
	Offset        int64                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`                        // Offset in the full image
	TotalSize     int64                  `protobuf:"varint,3,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"` // Total image size
	IsLast        bool                   `protobuf:"varint,4,opt,name=is_last,json=isLast,proto3" json:"is_last,omitempty"`          // True if this is the last chunk
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModuleImageChunk) Reset() {
	*x = ModuleImageChunk{}
	mi := &file_v1_module_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModuleImageChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModuleImageChunk) ProtoMessage() {}

func (x *ModuleImageChunk) ProtoReflect() protoreflect.Message {
	mi := &file_v1_module_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModuleImageChunk.ProtoReflect.Descriptor instead.
func (*ModuleImageChunk) Descriptor() ([]byte, []int) {
	return file_v1_module_proto_rawDescGZIP(), []int{18}
}

func (x *ModuleImageChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ModuleImageChunk) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ModuleImageChunk) GetTotalSize() int64 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

func (x *ModuleImageChunk) GetIsLast() bool {
	if x != nil {
		return x.IsLast
	}
	return false
}

type VerifyModuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModuleId      string                 `protobuf:"bytes,1,opt,name=module_id,json=moduleId,proto3" json:"module_id,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Digest        string                 `protobuf:"bytes,3,opt,name=digest,proto3" json:"digest,omitempty"` // Client's computed digest
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyModuleRequest) Reset() {
	*x = VerifyModuleRequest{}
	mi := &file_v1_module_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyModuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyModuleRequest) ProtoMessage() {}

func (x *VerifyModuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_module_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyModuleRequest.ProtoReflect.Descriptor instead.
func (*VerifyModuleRequest) Descriptor() ([]byte, []int) {
	return file_v1_module_proto_rawDescGZIP(), []int{19}
}

func (x *VerifyModuleRequest) GetModuleId() string {
	if x != nil {
		return x.ModuleId
	}
	return ""
}

func (x *VerifyModuleRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *VerifyModuleRequest) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

type VerifyModuleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`                       // True if digest matches
	Manifest      []byte                 `protobuf:"bytes,2,opt,name=manifest,proto3" json:"manifest,omitempty"`                  // Serialized ModuleManifest
	Signature     []byte                 `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`                // Module signature for verification
	SignedBy      string                 `protobuf:"bytes,4,opt,name=signed_by,json=signedBy,proto3" json:"signed_by,omitempty"`  // Key ID that signed this module
	SignedAt      int64                  `protobuf:"varint,5,opt,name=signed_at,json=signedAt,proto3" json:"signed_at,omitempty"` // Unix timestamp when signed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyModuleResponse) Reset() {
	*x = VerifyModuleResponse{}
	mi := &file_v1_module_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyModuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyModuleResponse) ProtoMessage() {}

func (x *VerifyModuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_module_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyModuleResponse.ProtoReflect.Descriptor instead.
func (*VerifyModuleResponse) Descriptor() ([]byte, []int) {
	return file_v1_module_proto_rawDescGZIP(), []int{20}
}

func (x *VerifyModuleResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *VerifyModuleResponse) GetManifest() []byte {
	if x != nil {
		return x.Manifest
	}
	return nil
}

func (x *VerifyModuleResponse) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *VerifyModuleResponse) GetSignedBy() string {
	if x != nil {
		return x.SignedBy
	}
	return ""
}

func (x *VerifyModuleResponse) GetSignedAt() int64 {
	if x != nil {
		return x.SignedAt
	}
	return 0
}

var File_v1_module_proto protoreflect.FileDescriptor

const file_v1_module_proto_rawDesc = "" +
	"\n" +
	"\x0fv1/module.proto\x12\tgimpel.v1\"\xe8\x01\n" +
	"\x0eConnectionInfo\x12#\n" +
	"\rconnection_id\x18\x01 \x01(\tR\fconnectionId\x12\x1b\n" +
	"\tsource_ip\x18\x02 \x01(\tR\bsourceIp\x12\x1f\n" +
	"\vsource_port\x18\x03 \x01(\rR\n" +
	"sourcePort\x12\x17\n" +
	"\adest_ip\x18\x04 \x01(\tR\x06destIp\x12\x1b\n" +
	"\tdest_port\x18\x05 \x01(\rR\bdestPort\x12\x1a\n" +
	"\bprotocol\x18\x06 \x01(\tR\bprotocol\x12!\n" +
	"\ftimestamp_ns\x18\a \x01(\x03R\vtimestampNs\"T\n" +
	"\x17HandleConnectionRequest\x129\n" +
	"\n" +
	"connection\x18\x01 \x01(\v2\x19.gimpel.v1.ConnectionInfoR\n" +
	"connection\"S\n" +
	"\x18HandleConnectionResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x1b\n" +
	"\tdata_port\x18\x02 \x01(\x05R\bdataPort\"\x14\n" +
	"\x12HealthCheckRequest\"\xce\x01\n" +
	"\x13HealthCheckResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12H\n" +
	"\bmetadata\x18\x03 \x03(\v2,.gimpel.v1.HealthCheckResponse.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8c\x01\n" +
	"\x0eModuleManifest\x12\x1b\n" +
	"\tmodule_id\x18\x01 \x01(\tR\bmoduleId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12%\n" +
	"\x0epayload_sha256\x18\x03 \x01(\tR\rpayloadSha256\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\"\xf4\x05\n" +
	"\vModuleImage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1b\n" +
	"\timage_ref\x18\x05 \x01(\tR\bimageRef\x12\x16\n" +
	"\x06digest\x18\x06 \x01(\tR\x06digest\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\a \x01(\x03R\tsizeBytes\x12\x1a\n" +
	"\bmanifest\x18\b \x01(\fR\bmanifest\x12\x1c\n" +
	"\tsignature\x18\t \x01(\fR\tsignature\x12\x1b\n" +
	"\tsigned_by\x18\n" +
	" \x01(\tR\bsignedBy\x12\x1b\n" +
	"\tsigned_at\x18\v \x01(\x03R\bsignedAt\x123\n" +
	"\x15required_capabilities\x18\f \x03(\tR\x14requiredCapabilities\x12/\n" +
	"\x13requires_privileged\x18\r \x01(\bR\x12requiresPrivileged\x12*\n" +
	"\x11min_agent_version\x18\x0e \x01(\tR\x0fminAgentVersion\x127\n" +
	"\tprotocols\x18\x0f \x03(\v2\x19.gimpel.v1.ModuleProtocolR\tprotocols\x12=\n" +
	"\tresources\x18\x10 \x01(\v2\x1f.gimpel.v1.ResourceRequirementsR\tresources\x12:\n" +
	"\x06labels\x18\x11 \x03(\v2\".gimpel.v1.ModuleImage.LabelsEntryR\x06labels\x12\x1d\n" +
	"\n" +
	"created_at\x18\x12 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x13 \x01(\x03R\tupdatedAt\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"r\n" +
	"\x0eModuleProtocol\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\fdefault_port\x18\x02 \x01(\rR\vdefaultPort\x12)\n" +
	"\x10high_interaction\x18\x03 \x01(\bR\x0fhighInteraction\"s\n" +
	"\x14ResourceRequirements\x12\x1b\n" +
	"\tmemory_mb\x18\x01 \x01(\x03R\bmemoryMb\x12%\n" +
	"\x0ecpu_millicores\x18\x02 \x01(\x05R\rcpuMillicores\x12\x17\n" +
	"\adisk_mb\x18\x03 \x01(\x03R\x06diskMb\"\xb5\x01\n" +
	"\rModuleCatalog\x120\n" +
	"\amodules\x18\x01 \x03(\v2\x16.gimpel.v1.ModuleImageR\amodules\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x03R\aversion\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\x03R\tupdatedAt\x12\x1c\n" +
	"\tsignature\x18\x04 \x01(\fR\tsignature\x12\x1b\n" +
	"\tsigned_by\x18\x05 \x01(\tR\bsignedBy\"\x96\x03\n" +
	"\x10ModuleAssignment\x12\x1b\n" +
	"\tmodule_id\x18\x01 \x01(\tR\bmoduleId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12;\n" +
	"\tlisteners\x18\x03 \x03(\v2\x1d.gimpel.v1.ListenerAssignmentR\tlisteners\x126\n" +
	"\x03env\x18\x04 \x03(\v2$.gimpel.v1.ModuleAssignment.EnvEntryR\x03env\x12N\n" +
	"\x12resource_overrides\x18\x05 \x01(\v2\x1f.gimpel.v1.ResourceRequirementsR\x11resourceOverrides\x12%\n" +
	"\x0eexecution_mode\x18\x06 \x01(\tR\rexecutionMode\x12'\n" +
	"\x0fconnection_mode\x18\a \x01(\tR\x0econnectionMode\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x7f\n" +
	"\x12ListenerAssignment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bprotocol\x18\x02 \x01(\tR\bprotocol\x12\x12\n" +
	"\x04port\x18\x03 \x01(\rR\x04port\x12)\n" +
	"\x10high_interaction\x18\x04 \x01(\bR\x0fhighInteraction\"\xa5\x01\n" +
	"\x11AgentModuleConfig\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12=\n" +
	"\vassignments\x18\x02 \x03(\v2\x1b.gimpel.v1.ModuleAssignmentR\vassignments\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x03R\aversion\x12\x1c\n" +
	"\tsignature\x18\x04 \x01(\fR\tsignature\"<\n" +
	"\x11GetCatalogRequest\x12'\n" +
	"\x0fcurrent_version\x18\x01 \x01(\x03R\x0ecurrentVersion\"b\n" +
	"\x12GetCatalogResponse\x12\x18\n" +
	"\aupdated\x18\x01 \x01(\bR\aupdated\x122\n" +
	"\acatalog\x18\x02 \x01(\v2\x18.gimpel.v1.ModuleCatalogR\acatalog\"a\n" +
	"\x1bGetModuleAssignmentsRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12'\n" +
	"\x0fcurrent_version\x18\x02 \x01(\x03R\x0ecurrentVersion\"n\n" +
	"\x1cGetModuleAssignmentsResponse\x12\x18\n" +
	"\aupdated\x18\x01 \x01(\bR\aupdated\x124\n" +
	"\x06config\x18\x02 \x01(\v2\x1c.gimpel.v1.AgentModuleConfigR\x06config\"N\n" +
	"\x15DownloadModuleRequest\x12\x1b\n" +
	"\tmodule_id\x18\x01 \x01(\tR\bmoduleId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\"v\n" +
	"\x10ModuleImageChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\x12\x1d\n" +
	"\n" +
	"total_size\x18\x03 \x01(\x03R\ttotalSize\x12\x17\n" +
	"\ais_last\x18\x04 \x01(\bR\x06isLast\"d\n" +
	"\x13VerifyModuleRequest\x12\x1b\n" +
	"\tmodule_id\x18\x01 \x01(\tR\bmoduleId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x16\n" +
	"\x06digest\x18\x03 \x01(\tR\x06digest\"\xa0\x01\n" +
	"\x14VerifyModuleResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x1a\n" +
	"\bmanifest\x18\x02 \x01(\fR\bmanifest\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\fR\tsignature\x12\x1b\n" +
	"\tsigned_by\x18\x04 \x01(\tR\bsignedBy\x12\x1b\n" +
	"\tsigned_at\x18\x05 \x01(\x03R\bsignedAt2\xba\x01\n" +
	"\rModuleService\x12[\n" +
	"\x10HandleConnection\x12\".gimpel.v1.HandleConnectionRequest\x1a#.gimpel.v1.HandleConnectionResponse\x12L\n" +
	"\vHealthCheck\x12\x1d.gimpel.v1.HealthCheckRequest\x1a\x1e.gimpel.v1.HealthCheckResponse2\xee\x02\n" +
	"\x14ModuleCatalogService\x12I\n" +
	"\n" +
	"GetCatalog\x12\x1c.gimpel.v1.GetCatalogRequest\x1a\x1d.gimpel.v1.GetCatalogResponse\x12g\n" +
	"\x14GetModuleAssignments\x12&.gimpel.v1.GetModuleAssignmentsRequest\x1a'.gimpel.v1.GetModuleAssignmentsResponse\x12Q\n" +
	"\x0eDownloadModule\x12 .gimpel.v1.DownloadModuleRequest\x1a\x1b.gimpel.v1.ModuleImageChunk0\x01\x12O\n" +
	"\fVerifyModule\x12\x1e.gimpel.v1.VerifyModuleRequest\x1a\x1f.gimpel.v1.VerifyModuleResponseB5Z3github.com/nohaxxjustlags/gimpel/api/go/v1;gimpelv1b\x06proto3"

var (
	file_v1_module_proto_rawDescOnce sync.Once
	file_v1_module_proto_rawDescData []byte
)

func file_v1_module_proto_rawDescGZIP() []byte {
	file_v1_module_proto_rawDescOnce.Do(func() {
		file_v1_module_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_module_proto_rawDesc), len(file_v1_module_proto_rawDesc)))
	})
	return file_v1_module_proto_rawDescData
}

var file_v1_module_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_v1_module_proto_goTypes = []any{
	(*ConnectionInfo)(nil),               // 0: gimpel.v1.ConnectionInfo
	(*HandleConnectionRequest)(nil),      // 1: gimpel.v1.HandleConnectionRequest
	(*HandleConnectionResponse)(nil),     // 2: gimpel.v1.HandleConnectionResponse
	(*HealthCheckRequest)(nil),           // 3: gimpel.v1.HealthCheckRequest
	(*HealthCheckResponse)(nil),          // 4: gimpel.v1.HealthCheckResponse
	(*ModuleManifest)(nil),               // 5: gimpel.v1.ModuleManifest
	(*ModuleImage)(nil),                  // 6: gimpel.v1.ModuleImage
	(*ModuleProtocol)(nil),               // 7: gimpel.v1.ModuleProtocol
	(*ResourceRequirements)(nil),         // 8: gimpel.v1.ResourceRequirements
	(*ModuleCatalog)(nil),                // 9: gimpel.v1.ModuleCatalog
	(*ModuleAssignment)(nil),             // 10: gimpel.v1.ModuleAssignment
	(*ListenerAssignment)(nil),           // 11: gimpel.v1.ListenerAssignment
	(*AgentModuleConfig)(nil),            // 12: gimpel.v1.AgentModuleConfig
	(*GetCatalogRequest)(nil),            // 13: gimpel.v1.GetCatalogRequest
	(*GetCatalogResponse)(nil),           // 14: gimpel.v1.GetCatalogResponse
	(*GetModuleAssignmentsRequest)(nil),  // 15: gimpel.v1.GetModuleAssignmentsRequest
	(*GetModuleAssignmentsResponse)(nil), // 16: gimpel.v1.GetModuleAssignmentsResponse
	(*DownloadModuleRequest)(nil),        // 17: gimpel.v1.DownloadModuleRequest
	(*ModuleImageChunk)(nil),             // 18: gimpel.v1.ModuleImageChunk
	(*VerifyModuleRequest)(nil),          // 19: gimpel.v1.VerifyModuleRequest
	(*VerifyModuleResponse)(nil),         // 20: gimpel.v1.VerifyModuleResponse
	nil,                                  // 21: gimpel.v1.HealthCheckResponse.MetadataEntry
	nil,                                  // 22: gimpel.v1.ModuleImage.LabelsEntry
	nil,                                  // 23: gimpel.v1.ModuleAssignment.EnvEntry
}
var file_v1_module_proto_depIdxs = []int32{
	0,  // 0: gimpel.v1.HandleConnectionRequest.connection:type_name -> gimpel.v1.ConnectionInfo
	21, // 1: gimpel.v1.HealthCheckResponse.metadata:type_name -> gimpel.v1.HealthCheckResponse.MetadataEntry
	7,  // 2: gimpel.v1.ModuleImage.protocols:type_name -> gimpel.v1.ModuleProtocol
	8,  // 3: gimpel.v1.ModuleImage.resources:type_name -> gimpel.v1.ResourceRequirements
	22, // 4: gimpel.v1.ModuleImage.labels:type_name -> gimpel.v1.ModuleImage.LabelsEntry
	6,  // 5: gimpel.v1.ModuleCatalog.modules:type_name -> gimpel.v1.ModuleImage
	11, // 6: gimpel.v1.ModuleAssignment.listeners:type_name -> gimpel.v1.ListenerAssignment
	23, // 7: gimpel.v1.ModuleAssignment.env:type_name -> gimpel.v1.ModuleAssignment.EnvEntry
	8,  // 8: gimpel.v1.ModuleAssignment.resource_overrides:type_name -> gimpel.v1.ResourceRequirements
	10, // 9: gimpel.v1.AgentModuleConfig.assignments:type_name -> gimpel.v1.ModuleAssignment
	9,  // 10: gimpel.v1.GetCatalogResponse.catalog:type_name -> gimpel.v1.ModuleCatalog
	12, // 11: gimpel.v1.GetModuleAssignmentsResponse.config:type_name -> gimpel.v1.AgentModuleConfig
	1,  // 12: gimpel.v1.ModuleService.HandleConnection:input_type -> gimpel.v1.HandleConnectionRequest
	3,  // 13: gimpel.v1.ModuleService.HealthCheck:input_type -> gimpel.v1.HealthCheckRequest
	13, // 14: gimpel.v1.ModuleCatalogService.GetCatalog:input_type -> gimpel.v1.GetCatalogRequest
	15, // 15: gimpel.v1.ModuleCatalogService.GetModuleAssignments:input_type -> gimpel.v1.GetModuleAssignmentsRequest
	17, // 16: gimpel.v1.ModuleCatalogService.DownloadModule:input_type -> gimpel.v1.DownloadModuleRequest
	19, // 17: gimpel.v1.ModuleCatalogService.VerifyModule:input_type -> gimpel.v1.VerifyModuleRequest
	2,  // 18: gimpel.v1.ModuleService.HandleConnection:output_type -> gimpel.v1.HandleConnectionResponse
	4,  // 19: gimpel.v1.ModuleService.HealthCheck:output_type -> gimpel.v1.HealthCheckResponse
	14, // 20: gimpel.v1.ModuleCatalogService.GetCatalog:output_type -> gimpel.v1.GetCatalogResponse
	16, // 21: gimpel.v1.ModuleCatalogService.GetModuleAssignments:output_type -> gimpel.v1.GetModuleAssignmentsResponse
	18, // 22: gimpel.v1.ModuleCatalogService.DownloadModule:output_type -> gimpel.v1.ModuleImageChunk
	20, // 23: gimpel.v1.ModuleCatalogService.VerifyModule:output_type -> gimpel.v1.VerifyModuleResponse
	18, // [18:24] is the sub-list for method output_type
	12, // [12:18] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_v1_module_proto_init() }
func file_v1_module_proto_init() {
	if File_v1_module_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_module_proto_rawDesc), len(file_v1_module_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_v1_module_proto_goTypes,
		DependencyIndexes: file_v1_module_proto_depIdxs,
		MessageInfos:      file_v1_module_proto_msgTypes,
	}.Build()
	File_v1_module_proto = out.File
	file_v1_module_proto_goTypes = nil
	file_v1_module_proto_depIdxs = nil
}
